name: flutterapp
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: # Version 3.0.9
  auto_route: # Version 0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: # Version 0.4.0
  build_runner: # Version 1.8.1

flutter:
  uses-material-design: true
